"""
Validation check registry for ResXR pipeline.

Manages registration and execution of quality validation checks.
"""

from __future__ import annotations

from typing import Protocol

from ..core.config import ValidationConfig
from ..core.constants import TrackingSystem
from ..core.logger import get_logger
from ..core.session import QualityFlag, Session, TrackingStream

logger = get_logger(__name__)


class ValidationCheck(Protocol):
    """
    Protocol defining the interface for validation checks.

    Attributes
    ----------
    name : str
        Unique identifier for this check
    description : str
        Human-readable description
    required_streams : Optional[List[TrackingSystem]]
        If set, declares which tracking systems this check needs access to.
        Multi-stream checks will only run once (when processing the first
        stream in the list) and can access other streams via session.get_stream().
        If not set, check runs independently on each stream.
    """

    name: str
    description: str
    required_streams: list[TrackingSystem] | None

    def __call__(
        self, stream: TrackingStream, session: Session, config: ValidationConfig
    ) -> list[QualityFlag]:
        """Run the check and return any quality flags."""
        ...


class CheckRegistry:
    """
    Registry for validation checks with enable/disable control.

    Validation checks are registered with a name and can be selectively
    enabled via configuration.
    """

    def __init__(self):
        self._checks: dict[str, ValidationCheck] = {}
        self._failed_checks: list[tuple[str, str, str]] = []

    def register(self, check: ValidationCheck) -> None:
        """
        Register a validation check.

        Parameters
        ----------
        check : ValidationCheck
            Check instance with name attribute
        """
        self._checks[check.name] = check
        logger.debug(f"Registered check: {check.name}")

    def get_check(self, name: str) -> ValidationCheck | None:
        """Get a check by name."""
        return self._checks.get(name)

    def get_enabled_checks(self, enabled_names: list[str]) -> list[ValidationCheck]:
        """
        Get list of enabled checks.

        Parameters
        ----------
        enabled_names : List[str]
            Names of checks to enable

        Returns
        -------
        List[ValidationCheck]
            List of enabled check instances
        """
        return [self._checks[name] for name in enabled_names if name in self._checks]

    def run_all(
        self, stream: TrackingStream, session: Session, config: ValidationConfig
    ) -> list[QualityFlag]:
        """
        Run all enabled checks on a stream.

        For multi-stream checks (those with required_streams defined),
        the check will only run once when processing the first stream
        in required_streams, and can access other streams via session.

        Parameters
        ----------
        stream : TrackingStream
            Stream to validate
        session : Session
            Parent session
        config : ValidationConfig
            Validation configuration

        Returns
        -------
        List[QualityFlag]
            All flags generated by enabled checks
        """
        flags = []
        enabled_checks = self.get_enabled_checks(config.enabled_checks)

        for check in enabled_checks:
            try:
                # Check if this check requires multiple streams
                required_streams = getattr(check, "required_streams", None)

                if required_streams:
                    # Multi-stream check: verify all required streams exist
                    missing = [s for s in required_streams if not session.has_stream(s)]
                    if missing:
                        logger.debug(
                            f"Skipping check '{check.name}': missing required "
                            f"streams {[s.value for s in missing]}"
                        )
                        continue

                    # Only run when processing the first required stream
                    # to avoid running the same check multiple times
                    if stream.system != required_streams[0]:
                        continue

                    logger.debug(
                        f"Running multi-stream check '{check.name}' with "
                        f"streams: {[s.value for s in required_streams]}"
                    )

                check_flags = check(stream, session, config)
                flags.extend(check_flags)
                logger.debug(
                    f"Check '{check.name}' on {stream.system.value}: {len(check_flags)} flags"
                )
            except Exception as e:
                logger.error(
                    "Check '%s' failed on %s — no flags produced for this "
                    "check. Downstream derivative data may contain unmasked "
                    "bad segments. Error: %s",
                    check.name,
                    stream.system.value,
                    e,
                )
                self._failed_checks.append((check.name, stream.system.value, str(e)))

        return flags

    @property
    def available_checks(self) -> list[str]:
        """List of all registered check names."""
        return list(self._checks.keys())

    @property
    def failed_checks(self) -> list[tuple[str, str, str]]:
        """List of (check_name, system, error) for checks that raised."""
        return list(self._failed_checks)

    def clear_failed_checks(self) -> None:
        """Reset the failed-checks list. Call between sessions in batch runs."""
        self._failed_checks.clear()


# Global registry instance
check_registry = CheckRegistry()


def register_check(check: ValidationCheck) -> ValidationCheck:
    """
    Decorator to register a validation check.

    Usage:
        @register_check
        class MyCheck:
            name = "my_check"
            ...
    """
    check_registry.register(check)
    return check
